### ISSUE TITLE
HSR's Web Cache location may have changed, breaking the automatic retrieval

### ISSUE THREAD

**Issue by technizor** [Ennea/warp-journal#7]
Instead of generating all of the webCaches sub-directories (e.g. blob_storage, Cache, databases) as direct descendants, my install (custom location, Win11) has a versioned subfolder (`webCaches/2.14.0.0`) with those same webCaches sub-directories under it that have been very recently updated by the game after playing. Note that this versioned subfolder may be different for other installs, or subject to change with future HSR updates.

The old path `webCaches/Cache/Cache_Data/data_2` which is used by the powershell script is no longer updated. The new path according to my own installation is `webCaches/2.14.0.0/Cache/Cache_Data/data_2`

Opening the new log file location manually after opening records, closing HSR, and then searching for the most recent instance of `https://api-os-takumi.mihoyo.com/common/gacha_record/api/getGachaLog` finds the URL needed for Manual Mode, which is undocumented and requires code repo diving to determine.

Consider including instructions in the Manual Mode UI on which URL to search for within those webCache files to make the manual mode more resilient to these types of upstream changes to the HSR webCache.

**Comment by Ennea** [comment]
Genshin had the same path change, so I'm guessing they've updated the in-game browser they use in HSR to the same version they now use in Genshin.

Edit: _Almost_ the same. Similar version, then 😋
